# It's not necessary to copy all keys to your config.
# If the key is missing in your config, "default-config.toml" will serve as a fallback
start-at-login = true
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# after-startup-command = [
#   # JankyBorders
#   'exec-and-forget borders active_color=0xffc3e88d inactive_color=0xff494d64 width=4.0',
# ]

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 6
inner.vertical = 6
outer.left = 6
outer.bottom = 6
outer.top = 6
outer.right = 6

# =======================================================
# BINDINGS
# https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# =======================================================
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right
# All possible modifiers: cmd, alt, ctrl, shift
# All possible commands:  https://nikitabobko.github.io/AeroSpace/commands

# 'main' binding mode must be always presented
[mode.main.binding]

# LAUNCHER TERMINALS
alt-ctrl-cmd-t = 'exec-and-forget open -n /Applications/WezTerm.app'
# LAUNCHER FINDERS
alt-ctrl-cmd-space = 'exec-and-forget open .'
alt-ctrl-cmd-y = 'exec-and-forget wezterm start -- yazi'
# LAUNCHER BROWSERS
alt-ctrl-cmd-b = 'exec-and-forget open -n "/Applications/Brave Browser.app"'
alt-ctrl-cmd-f = 'exec-and-forget open -n "/Applications/Firefox.app"'
alt-ctrl-cmd-c = 'exec-and-forget open -n "/Applications/Google Chrome.app"'
# LAUNCHER APPLICATIONS
alt-ctrl-cmd-s = 'exec-and-forget open -n "/Applications/Spotify.app"'
alt-ctrl-cmd-k = 'exec-and-forget open -n "/Applications/Slack.app"'
alt-ctrl-cmd-n = 'exec-and-forget wezterm start -- nvim'
alt-ctrl-cmd-u = 'exec-and-forget wezterm start -- nu'

# LAYOUTS
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# WINDOWS
alt-x = 'close'
alt-ctrl-x = 'close-all-windows-but-current'
alt-f = 'fullscreen'
cmd-h = []                                   # DISABLE NATIVE WINDOW HIDE
# WINDOW FOCUS
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'
# WINDOW MOVE
alt-ctrl-h = 'move left'
alt-ctrl-j = 'move down'
alt-ctrl-k = 'move up'
alt-ctrl-l = 'move right'
# WINDOW RESIZE
alt-ctrl-minus = 'resize smart -50'
alt-ctrl-equal = 'resize smart +50'

# WORKSPACES
alt-tab = 'workspace-back-and-forth'
alt-ctrl-tab = 'move-workspace-to-monitor --wrap-around next'
# WOWRKSPACE FOCUS
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
# WORKSPACES MOVE WINDOW
alt-ctrl-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-ctrl-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-ctrl-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-ctrl-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-ctrl-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-ctrl-6 = ['move-node-to-workspace 6', 'workspace 6']
alt-ctrl-7 = ['move-node-to-workspace 7', 'workspace 7']
alt-ctrl-8 = ['move-node-to-workspace 8', 'workspace 8']
alt-ctrl-9 = ['move-node-to-workspace 9', 'workspace 9']

# CUSTOM MODES
# alt-shift-semicolon = 'mode service'
# WORKSPACE MOVE WINDOW TO
